services:
  - type: web
    name: quiz-platform-backend
    env: node
    root: Backend
    buildCommand: npm install
    startCommand: node app.js
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: CONNECTION_URL
        sync: false
